//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fulbert.Presentation.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fulbert.Presentation.Localization.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wizytę.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy pacjent.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulbert.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu/komórkowy.
        /// </summary>
        public static string ContactCellPhone {
            get {
                return ResourceManager.GetString("ContactCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string ContactCity {
            get {
                return ResourceManager.GetString("ContactCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres mailowy.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo/Region.
        /// </summary>
        public static string ContactState {
            get {
                return ResourceManager.GetString("ContactState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string ContactStreet {
            get {
                return ResourceManager.GetString("ContactStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string ContactZipCode {
            get {
                return ResourceManager.GetString("ContactZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer PESEL musi zawierać dokładnie 11 liczb!.
        /// </summary>
        public static string ErrorPeselFormat {
            get {
                return ResourceManager.GetString("ErrorPeselFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten numer pesel jest błędny!.
        /// </summary>
        public static string ErrorPeselValidation {
            get {
                return ResourceManager.GetString("ErrorPeselValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pole nie może być puste!.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek {0} lat..
        /// </summary>
        public static string FormatAge {
            get {
                return ResourceManager.GetString("FormatAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data urodzenia {0:dd.MM.yyyy} roku..
        /// </summary>
        public static string FormatBirthday {
            get {
                return ResourceManager.GetString("FormatBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy to kobieta? {0}.
        /// </summary>
        public static string FormatGender {
            get {
                return ResourceManager.GetString("FormatGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulbert - aplikacja osobistej mini przychodni.
        /// </summary>
        public static string FullAppName {
            get {
                return ResourceManager.GetString("FullAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizyty pacjenta.
        /// </summary>
        public static string PatientAppointments {
            get {
                return ResourceManager.GetString("PatientAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane teleadresowe pacjenta.
        /// </summary>
        public static string PatientContactDetails {
            get {
                return ResourceManager.GetString("PatientContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane personalne pacjenta.
        /// </summary>
        public static string PatientData {
            get {
                return ResourceManager.GetString("PatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista pacjentów.
        /// </summary>
        public static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moduł pacjenta.
        /// </summary>
        public static string PatientModule {
            get {
                return ResourceManager.GetString("PatientModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wizyta pacjenta.
        /// </summary>
        public static string PatientNewAppointment {
            get {
                return ResourceManager.GetString("PatientNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        public static string Pesel {
            get {
                return ResourceManager.GetString("Pesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer PESEL jest błędny!.
        /// </summary>
        public static string PeselIncorrect {
            get {
                return ResourceManager.GetString("PeselIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer PESEL.
        /// </summary>
        public static string PeselNumber {
            get {
                return ResourceManager.GetString("PeselNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer PESEL jest za krótki!.
        /// </summary>
        public static string PeselTooShort {
            get {
                return ResourceManager.GetString("PeselTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano dane nowego pacjenta.
        /// </summary>
        public static string SavedNewPatientData {
            get {
                return ResourceManager.GetString("SavedNewPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaktualizowano dane pacjenta.
        /// </summary>
        public static string SavedPatientData {
            get {
                return ResourceManager.GetString("SavedPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz dane pacjenta.
        /// </summary>
        public static string SavePatientData {
            get {
                return ResourceManager.GetString("SavePatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz frazę do wyszukania.
        /// </summary>
        public static string SearchPhrase {
            get {
                return ResourceManager.GetString("SearchPhrase", resourceCulture);
            }
        }
    }
}
